### ISSUE TITLE
audit profile configuration not working

### ISSUE THREAD

**Issue by noloc** [chef-cookbooks/audit#240]
### Cookbook version
audit 4.0.1

### Chef-client version
chef-client 12.20.3

### Platform Details
RedHat Linux release 7.3 (Maipo)

### Scenario:
Newly instantiated hosts do not auto-register in to the Chef Compliance server since they can't run the audit cookbook successfully.  I would typically see the message warning me about no profiles being defined...  and the cookbook exits with no issues.  

But the node does not auto register to the Chef Compliance server and therefore, the issue I am trying to address.

### Steps to Reproduce:
When I add attributes for the profiles to my wrapper cookbook, which depends on the audit cookbook I see many errors and a 403 error that I can't find how to resolve:

My wrapper cookbook attributes default.rb contains:
default['audit']['reporter'] = 'chef-server-compliance'
default['audit']['fetcher'] = 'chef-server'
default['audit']['profiles'] = [
  {
    'name': 'Base Apache',
    'compliance': 'base/apache'
  },
  {
    'name': 'Base Linux',
    'compliance': 'base/linux'
  },
  {
    'name': 'Base SSH',
    'compliance': 'base/ssh'
  }

My wrapper cookbook recipe simply has:  include_recipe 'audit::default'
My metadata.rb simply has:  depends 'audit'

### Expected Result:
1) Get nodes to successfully run the audit cookbook and,
2) Auto registration to the Chef Compliance server

### Actual Result:
I typically see in the output of the chef-client run:

[2017-06-13T16:38:12-04:00] DEBUG: HOST: some_host_name.com:443
[2017-06-13T16:38:12-04:00] DEBUG: X-REMOTE-REQUEST-ID: d07ae1e0-0aa8-4f08-aae3-ae9799b64fa7
[2017-06-13T16:38:12-04:00] DEBUG: ---- End HTTP Request Header Data ----
[2017-06-13T16:38:12-04:00] DEBUG: ---- HTTP Status and Header Data: ----
[2017-06-13T16:38:12-04:00] DEBUG: HTTP 1.1 403 Forbidden
[2017-06-13T16:38:12-04:00] DEBUG: server: openresty/1.11.2.1
[2017-06-13T16:38:12-04:00] DEBUG: date: Tue, 13 Jun 2017 20:38:12 GMT
[2017-06-13T16:38:12-04:00] DEBUG: content-type: text/html
[2017-06-13T16:38:12-04:00] DEBUG: transfer-encoding: chunked
[2017-06-13T16:38:12-04:00] DEBUG: connection: close

Followed by many lines of:

[2017-06-13T16:38:12-04:00] DEBUG: content-encoding: gzip
[2017-06-13T16:38:12-04:00] DEBUG: ---- End HTTP Status/Header Data ----
[2017-06-13T16:38:12-04:00] DEBUG: ---- HTTP Response Body ----
[2017-06-13T16:38:12-04:00] DEBUG: ]▒A▒0
                                        ▒H▒C▒▒zts▒▒▒H▒4F▒R▒ߓ@▒▒gG▒▒▒[▒É߽%▒▒▒▒▒▒x▒▒▒▒    ▒▒▒TՉ?F▒X%IY▒=D▒▒r▒▒▒▒▒*▒K▒▒
                                    ▒▒4▒▒b▒W▒6ժ▒▒▒▒^▒د
[2017-06-13T16:38:12-04:00] DEBUG: ---- End HTTP Response Body -----
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: No content-length information collected for the streamed download, cannot identify streamed download.
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::APIVersions#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_stream_complete
[2017-06-13T16:38:12-04:00] DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_stream_complete
[2017-06-13T16:38:12-04:00] INFO: HTTP Request Returned 403 Forbidden:
[2017-06-13T16:38:12-04:00] ERROR: 403 "Forbidden" (Net::HTTPServerException)
/opt/chef/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.20.3/lib/chef/http.rb:214:in `streaming_request'
/var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:87:in `block in download_archive_to_temp'
/var/chef/cache/cookbooks/audit/libraries/helper.rb:45:in `with_http_rescue'
/var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:86:in `download_archive_to_temp'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/fetchers/url.rb:120:in `temp_archive_path'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/fetchers/url.rb:103:in `sha256'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/fetchers/url.rb:93:in `cache_key'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/inspec/cached_fetcher.rb:32:in `cache_key'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/inspec/cached_fetcher.rb:39:in `fetch'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/inspec/profile.rb:71:in `for_fetcher'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/inspec/profile.rb:78:in `for_target'
/opt/chef/embedded/lib/ruby/gems/2.3.0/gems/inspec-1.25.1/lib/inspec/runner.rb:169:in `add_target'

**Comment by mike-stewart** [comment]
I'm seeing this error as well. 

Versions:
inspec 1.31.1
audit 4.1.0
chef-client 12.15.19

Any idea if there's a workaround? @noloc @chris-rock

**Comment by kekaichinose** [comment]
@noloc @mike-stewart is this still an issue on the current versions of Chef Infra (chef-client), Chef InSpec, and audit cookbook?

**Comment by kekaichinose** [comment]
Thank you for tracking down this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities. We very much appreciate you bringing this to our attention. If this is still an issue for you, please create a new issue and include data that is current to the latest platform versions.

Thank you!
__Chef InSpec Team__
