### ISSUE TITLE
Audit 5.0.0 - NoMethodError: undefined method `path' for nil:NilClass when profile not found

### ISSUE THREAD

**Issue by sean-horn** [chef-cookbooks/audit#301]
### Cookbook version
5.0.0

### Chef-client version
12.19.36

### Automate version

1.7.10 with the built-in Compliance activated

### Platform Details
CentOS 7.3.1611

### Scenario:

If I ask for a profile that doesn't exist on the Automate system, I get a confusing result from the audit recipe run. Seems to be the same as issue #39 

### Steps to Reproduce:
* Install Automate 1.7.10
* Activate Compliance
* Do not upload a profile for which the audit cookbook will ask during its run.
* Notice the output is a big ol' backtrace, preceded by a 404.

### Expected Result:

Audit recipe fails and reports something like "I couldn't find the requested profile BLAH on the Automate system". I get that the 404 is right there, but that's not going to make sense to a typical user of this cookbook, especially when combined with the weird `[2017-12-28T23:36:39+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `path' for nil:NilClass>` found later in the stacktrace.

### Actual Result:

```
[2017-12-28T23:36:38+00:00] INFO: Chef Run complete in 5.898268208 seconds

Running handlers:
[2017-12-28T23:36:38+00:00] INFO: Running report handlers
[2017-12-28T23:36:38+00:00] INFO: Just after load deps and fetcher
[2017-12-28T23:36:38+00:00] INFO: Just after login_to_compliance
[2017-12-28T23:36:38+00:00] INFO: Just before get_opts
[2017-12-28T23:36:38+00:00] WARN: Format is json
[2017-12-28T23:36:38+00:00] INFO: Using InSpec 1.46.2
[2017-12-28T23:36:39+00:00] INFO: Fetching profile from: https://chef-432.lxc/compliance/organizations/delivery/owners/admin/compliance/cis-redhat6/tar
[2017-12-28T23:36:39+00:00] INFO: HTTP Request Returned 404 Not Found:
[2017-12-28T23:36:39+00:00] ERROR: 404 "Not Found" (Net::HTTPServerException)
/opt/chefdk/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/http.rb:214:in `streaming_request'
/var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:88:in `block in download_archive_to_temp'
/var/chef/cache/cookbooks/audit/libraries/helper.rb:45:in `with_http_rescue'
/var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:87:in `download_archive_to_temp'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/fetchers/url.rb:139:in `temp_archive_path'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/fetchers/url.rb:122:in `sha256'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/fetchers/url.rb:112:in `cache_key'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/inspec/cached_fetcher.rb:32:in `cache_key'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/inspec/cached_fetcher.rb:39:in `fetch'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/inspec/profile.rb:71:in `for_fetcher'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/inspec/profile.rb:78:in `for_target'
/root/.chefdk/gem/ruby/2.3.0/gems/inspec-1.46.2/lib/inspec/runner.rb:170:in `add_target'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:148:in `block in call'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:148:in `each'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:148:in `call'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:66:in `report'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/handler.rb:259:in `run_report_unsafe'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:84:in `run_report_safely'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/handler.rb:125:in `block in run_report_handlers'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/handler.rb:123:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/handler.rb:123:in `run_report_handlers'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/handler.rb:135:in `block in <class:Handler>'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:441:in `block in run_completed_successfully'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:440:in `each'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:440:in `run_completed_successfully'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/client.rb:299:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:295:in `block in fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:283:in `fork_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:248:in `block in run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/local_mode.rb:44:in `with_server_connectivity'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:236:in `run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `loop'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:450:in `interval_run_chef_client'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application/client.rb:434:in `run_application'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/lib/chef/application.rb:59:in `run'
/opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.19.36/bin/chef-client:26:in `<top (required)>'
/usr/bin/chef-client:58:in `load'
/usr/bin/chef-client:58:in `<main>'
[2017-12-28T23:36:39+00:00] ERROR: Object does not exist on remote server.
[2017-12-28T23:36:39+00:00] ERROR: Received HTTP error 404
[2017-12-28T23:36:39+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `path' for nil:NilClass>
[2017-12-28T23:36:39+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:91:in `download_archive_to_temp'
```

**Comment by vsingh-msys** [comment]
Fixed in #321 & https://github.com/chef-cookbooks/audit/pull/349
