### ISSUE TITLE
Report handler Chef::Handler::AuditReport raised NoMethodError: undefined method 'path' for <String> when profile not found

### ISSUE THREAD

**Issue by vsingh-msys** [chef-cookbooks/audit#348]
### Cookbook version
7.3.0

### Chef-client version
14.8.12

### Platform Details
ubuntu 16.04

### Scenario:

If desired audit profiles are not available on chef-server/chef-automate, it's getting 404 response from server, but while humanizing error message it access `.path` on `@target` that causes `#<NoMethodError: undefined method 'path' for #<String:`

### Steps to Reproduce:
- Setup fetcher: `chef-server` and reporter: `chef-server-automate`.
```include_recipe 'audit::default'

node.default['audit']['reporter'] = 'chef-server-automate'
node.default['audit']['fetcher'] = 'chef-server'
```
- Add any profile which is not available on chef server.
```
node.default['audit']['profiles'].push(
  {
    'name': 'linux123',
    'compliance': 'base/linux'
  }
)
```
- Bootstrap a node with extended audit cookbook recipe. 

### Expected Result:

```Report handler Chef::Handler::AuditReport raised #<RuntimeError: Unable to find requested profile on path: 'https://chef-server2.test/compliance/organizations/workflow/owners/base/compliance/linux/tar' on the Automate system.>```

### Actual Result:

```Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method 'path' for #<String:0x0000000005f00eb0>>```

### Logs:
```
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: Object does not exist on remote server.
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: Received HTTP error 404
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: Report handler Chef::Handler::AuditReport raised #<NoMethodError: undefined method `path' for #<String:0x0000000005f00eb0>>
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/vendor/chef-server/fetcher.rb:102:in `download_archive_to_temp'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/fetchers/url.rb:152:in `temp_archive_path'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/fetchers/url.rb:132:in `sha256'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/plugins/inspec-compliance/lib/inspec-compliance/target.rb:29:in `sha256'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/fetchers/url.rb:117:in `cache_key'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/inspec/cached_fetcher.rb:32:in `cache_key'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/inspec/cached_fetcher.rb:39:in `fetch'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/inspec/profile.rb:72:in `for_fetcher'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/inspec/profile.rb:79:in `for_target'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.2.6/lib/inspec/runner.rb:197:in `add_target'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:170:in `block in call'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:170:in `each'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:170:in `call'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:81:in `report'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/handler.rb:257:in `run_report_unsafe'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:99:in `run_report_safely'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/handler.rb:123:in `block in run_report_handlers'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/handler.rb:121:in `each'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/handler.rb:121:in `run_report_handlers'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/handler.rb:133:in `block in <class:Handler>'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/client.rb:445:in `block in run_completed_successfully'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/client.rb:444:in `each'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/client.rb:444:in `run_completed_successfully'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/client.rb:301:in `run'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/application.rb:303:in `run_with_graceful_exit_option'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/application.rb:279:in `block in run_chef_client'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/local_mode.rb:44:in `with_server_connectivity'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/application.rb:261:in `run_chef_client'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/application/client.rb:440:in `run_application'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/lib/chef/application.rb:66:in `run'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/chef-14.8.12/bin/chef-client:25:in `<top (required)>'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /usr/bin/chef-client:74:in `load'
192.168.33.70 [2019-01-14T10:39:36+00:00] ERROR: /usr/bin/chef-client:74:in `<main>'
192.168.33.70   - Chef::Handler::AuditReport
192.168.33.70 Running handlers complete
192.168.33.70 Chef Client finished, 0/2 resources updated in 08 seconds
```

**Comment by vsingh-msys** [comment]
Fixed in https://github.com/chef-cookbooks/audit/pull/349
