### ISSUE TITLE
Undefined method 'path' for nil:NilClass

### ISSUE THREAD

**Issue by chef09210** [chef-cookbooks/audit#39]
### Cookbook version
0.5.0

### Chef-client version
12.9.38-1

### Platform Details
Windows 7 Enterprise

### Scenario:
Trying to run audit cookbook on node.

### Steps to Reproduce:
Execute a remote chef-client call using knife windows winrm that has the audit cookbook in the node's runlist

### Expected Result:
```
INFO: Processing compliance_profile[windows] action fetch (audit::default line 28)
WARN: Using inspec version: (0.19.3)
INFO: Fetch compliance profile base/windows
INFO: Processing directory[c:/chef/cache/compliance] action create (c:/chef/cache/cookbooks/audit/libraries/profile.rb line 40)
INFO: Processing directory[c:/chef/cache/compliance] action create (c:/chef/cache/cookbooks/audit/libraries/profile.rb line 40)
INFO: Processing compliance_profile[windows] action execute (audit::default line 28)
WARN: Using inspec version: (0.19.3)
INFO: Execute compliance profile base/windows
```
https://gist.github.com/chef09210/c8b116b747e340e5ba6afbe81d4adb62

### Actual Result:
```
================================================================================	
	[Error executing action `fetch` on resource 'compliance_profile[windows]'	
================================================================================	

	NoMethodError	
-------------	
undefined method `path' for nil:NilClass	

	Cookbook Trace:	
---------------	
c:/chef/cache/cookbooks/audit/libraries/profile.rb:71:in `block (2 levels) in <class:ComplianceProfile>'
	c:/chef/cache/cookbooks/audit/libraries/profile.rb:35:in `block in <class:ComplianceProfile>'	

	Resource Declaration:	
---------------------	
# In c:/chef/cache/cookbooks/audit/recipes/default.rb
	
	 28:   compliance_profile p do
	 29:     owner o
	 30:     server server
	 31:     token token
	 32:     inspec_version node['audit']['inspec_version']
	 33:     action [:fetch, :execute]
	 34:   end
	 35: end
	
	Compiled Resource:	
------------------	
# Declared in c:/chef/cache/cookbooks/audit/recipes/default.rb:28:in `block in from_file'
	
	compliance_profile("windows") do
	  action [:fetch, :execute]
	  retries 0
	  retry_delay 2
	  default_guard_interpreter :default
	  declared_type :compliance_profile
	  cookbook_name "audit"
	  recipe_name "default"
	  owner "base"
	  inspec_version "latest"
	  profile "windows"
	end
	
	Platform:	
---------	
x64-mingw32
```	
https://gist.github.com/chef09210/77b1e9d23118bf06864b3bbb8a88eb50

**Comment by alexpop** [comment]
Thanks for the bug report. I see you are using audit 0.5.0. I believe this issue has been fixed in this PR:
https://github.com/chef-cookbooks/audit/pull/35/files

Please give audit 0.6.0 a try and let us know if you are still having issues. Cheers!

**Comment by chef09210** [comment]
Hi alex,

That fixed the error message from appearing in the Chef log, but the underlying issue was due to a time synchronization issue. Thanks for the response.
