### ISSUE TITLE
Audit cookbook is not upgrading in production mode

### ISSUE THREAD

**Issue by vsingh-msys** [chef-cookbooks/audit#412]
### Cookbook version
8+, 9.0.1

### Chef-client version
14.10.9 --> 15+ or directly on chef-client 15

### Platform Details
RHEL 6, 7

### Scenario:
 While upgrading the chef-client 14 to chef-client 15 or directly installing chef 15, so audit cookbook https://github.com/chef-cookbooks/audit/commit/0016c975752e6ee57dcbe6f9cd0b064383b2d96d has been done for chef-15. But due to some reason, the latest(9.1.0 or 8.0.1) version of the audit cookbook is not fetching on RHEL 6,7 nodes on production mode.

### Steps to Reproduce:
Unexpected behavior showing here

Steps:
- Install and configure Chef Automate

- Install and configure Chef server 12+.

- Configure data collection with Automate.

- Bootstrap a vagrant RHEL 6 node with version 14.1.12, empty run list.

- Use audit cookbook and add compliances profiles admin/apache-baseline, admin/ssh-baseline, etc.

- created `auditviv` cookbook which depends on `audit` cookbooks

- Run chef-client -o auditviv on the node.

- Use cookbook chef_client_updater with version 3.2.9 and write a recipe to update chef-client.

- Add some other profiles in the custom auditviv cookbook recipe.

- Run chef-client -o auditviv on the node.

### Expected Result:
it would upgrade the chef-client and used the provided audit cookbook and send the report to the chef automate without fail. 

### Actual Result:

Comment from customer after manual inspection

```
/var/chef/cache/cookbooks/audit/recipes/default.rb is different on working and non working nodes.

On Working node:
unless Chef::Config[:audit_mode] == :disabled || Gem::Requirement.new('>= 15').satisfied_by?(Gem::Version.new(Chef::VERSION))

On non-working node:

unless Chef::Config[:audit_mode] == :disabled

```

```
sudo chef-client
Starting Chef Infra Client, version 15.2.20
resolving cookbooks for run list: ["auditviv::default"]
Synchronizing Cookbooks:
  - auditviv (0.2.16)
  - audit (8.0.1)
Installing Cookbook Gems:
Compiling Cookbooks...
Recipe: audit::inspec
  * inspec_gem[inspec] action install (up to date)
  Converging 1 resources
  * inspec_gem[inspec] action nothing (skipped due to action :nothing)

Running handlers:
[2019-09-09T12:00:48+00:00] WARN: Use of a hash array for the node['audit']['profiles'] is deprecated. Please refer to the README and use a hash of hashes.
controls/translated-controls.rb:2628: warning: regular expression has ']' without escape
[2019-09-09T12:00:53+00:00] WARN: Overwriting resource apache. To reference a specific version of apache use the resource() method
controls/translated-controls.rb:3285: warning: regular expression has ']' without escape
[2019-09-09T12:01:05+00:00] WARN: Compliance report size is 3.0 MB.
/var/chef/cache/cookbooks/audit/libraries/helper.rb:51: warning: constant Net::HTTPServerException is deprecated
[2019-09-09T12:01:05+00:00] ERROR: 400 "Bad Request" (Net::HTTPServerException)
/opt/chef/embedded/lib/ruby/2.6.0/net/http/response.rb:122:in `error!'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/http.rb:152:in `request'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/http.rb:131:in `post'
/var/chef/cache/cookbooks/audit/libraries/reporters/cs_automate.rb:37:in `block in send_report'
/var/chef/cache/cookbooks/audit/libraries/helper.rb:45:in `with_http_rescue'
/var/chef/cache/cookbooks/audit/libraries/reporters/cs_automate.rb:36:in `send_report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:246:in `send_report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:87:in `block in report'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:86:in `each'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:86:in `report'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:256:in `run_report_unsafe'
/var/chef/cache/cookbooks/audit/files/default/handler/audit_report.rb:99:in `run_report_safely'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:123:in `block in run_report_handlers'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:121:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:121:in `run_report_handlers'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/handler.rb:133:in `block in <class:Handler>'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:418:in `block in run_completed_successfully'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:417:in `each'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:417:in `run_completed_successfully'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/client.rb:293:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:320:in `run_with_graceful_exit_option'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:296:in `block in run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/local_mode.rb:42:in `with_server_connectivity'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:279:in `run_chef_client'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application/base.rb:330:in `run_application'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.2.20/lib/chef/application.rb:69:in `run'
/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-bin-15.2.20/bin/chef-client:25:in `<top (required)>'
/usr/bin/chef-client:162:in `load'
/usr/bin/chef-client:162:in `<main>'
[2019-09-09T12:01:05+00:00] ERROR: Received HTTP error 400
  - Chef::Handler::AuditReport
Running handlers complete
Chef Infra Client finished, 0/2 resources updated in 18 seconds

```

### Note: it showing audit cookbook version 8+ on the node but still picking the old version of the audit cookbooks

**Comment by btm** [comment]
We've tried reproducing this and now believe this is unrelated to the cookbook but rather is tied to the environment pins in the users environment.

If we get a reproduction case later, we can revisit this.
