### ISSUE TITLE
Gem dependency conflict between audit and chef client (14.15.6)

### ISSUE THREAD

**Issue by sintim** [chef-cookbooks/audit#423]
### Cookbook version
9.2.1

### Chef-client version
14.15.6

### Platform Details
Windows Server 2016 DataCenter

### Scenario:
We have some tests that make use of the audit cookbook to do some validations on Windows machines.  Previously we were using chef client 14.14.29 and the tests run fine.  However with 14.15.6 we are seeing errors about conflicting Gems  

### Steps to Reproduce:
have a machine set up with chef client 14.15.6 and run some tests against it.

### Expected Result:
Tests should be able to run.

### Actual Result:

[4/22 3:00 PM] Sin, Tim
    [2020-04-22T21:42:53+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-04-22T21:42:53+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: execute[inspec_s300_basevm_validation_tests] (s300_validation::s300_validate_basevm line 12) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
---- Begin output of inspec exec --no-distinct-exit profile-validation --input-file profile-validation/attributes/attributes-2020pu2.yml --reporter cli cli:c:/chefLogs/validationResults.log ----
STDOUT:
STDERR: C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:2332:in `raise_if_conflicts': Unable to activate pry-byebug-3.9.0, because pry-0.12.2 conflicts with pry (~> 0.13.0) (Gem::ConflictError)
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/specification.rb:1441:in `activate'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems.rb:217:in `try_activate'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:123:in `rescue in require'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:34:in `require'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-byebug-3.8.0/lib/pry-byebug/cli.rb:3:in `<top (required)>'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/plugins.rb:41:in `load_cli_options'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/cli.rb:37:in `block in add_plugin_options'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/cli.rb:36:in `each'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/cli.rb:36:in `add_plugin_options'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry/cli.rb:127:in `<top (required)>'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/pry-0.12.2/lib/pry.rb:121:in `<top (required)>'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.9.3/lib/inspec/shell.rb:5:in `<top (required)>'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.9.3/lib/inspec.rb:16:in `<top (required)>'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.9.3/bin/inspec:10:in `require_relative'
    from C:/opscode/chef/embedded/lib/ruby/gems/2.5.0/gems/inspec-core-3.9.3/bin/inspec:10:in `<top (required)>'
    from C:/opscode/chef/embedded/bin/inspec:23:in `load'
    from C:/opscode/chef/embedded/bin/inspec:23:in `<main>'
---- End output of inspec exec --no-distinct-exit profile-validation --input-file profile-
.....
returned 1

[2020-04-22T21:42:53+00:00] INFO: Child process exited (pid: 5112)
[2020-04-22T21:42:53+00:00] INFO: Next chef-client run will happen in 180.42489210324598 seconds
 
This is probably because of conflicting Gem libraries (See attached pictures).

![1](https://user-images.githubusercontent.com/8153932/81869131-5bd2e600-9528-11ea-9e90-b3dee81d4e9a.jpg)
![2](https://user-images.githubusercontent.com/8153932/81869134-5c6b7c80-9528-11ea-9572-61dd53153783.jpg)

Tests ran fine after I manually uninstalled method_source 1.0.0, pry 13, and pry-byebug 3.9

**Comment by james-stocks** [comment]
We changed the method-source dependency in InSpec to address this (in [this PR](https://github.com/inspec/inspec/pull/4992)) but haven't made the same change in InSpec 3.
We'll look at backporting this change into InSpec 3 but in the immediate term if you are able to update to the latest InSpec 4 that should also resolve this.
